### ISSUE TITLE
USER STORY: Admin hide the poll

### ISSUE THREAD

**Issue by CI-Tom** [CI-Tom/Agile-Project#6]
In order to **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll**

## Acceptance Criteria

a. The poll should disappear at 11:59PM on the target date
b. The real estate of the "Poll" should be reserved on the home page. A message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
c. The administrator expiry date should be at least 3 days after the current date.

## Tasks

- [x] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay Tuned, a new Poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days
- [ ] Create a job to check expired Polls every day at 11:59PM and hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
